### ISSUE TITLE
Implement module specific conda environments.

### ISSUE THREAD

**Issue by edg1983** [Biostatistics-Unit-HT/Flanders#8]
I'm opening this as a discussion on how to implement module-specific Conda environments. Since the backbone of the code is in R, this requires some extra effort compared to the usual Conda install. My idea is to use `renv` to keep stable R environments within Conda.

Compared to the current implementation, we need to create a self-contained R script for each module, eventually supported by a dedicated R package.

1. First, we need to identify the minimum set of dependencies for each module
2. Break down the current main functions file into module-depend units. 
3. We can either inject these functions directly into the script or make a dedicated R package. The point is to isolate dependencies and avoid sourcing from a big general source that loads libraries not needed in the specific module

We can then manage renv in conda like this. In theory, this works fine, but we'll need some testing.

1. Create a conda env with R and any additional non-R dependency.
2. Install `renv` in the conda env.

     ```bash
     conda activate your_env_name
     R -e "install.packages('renv')"
     ```

3. Initialize `renv` in the project and install needed packages:

     ```R
     library(renv)
     renv::init()
     renv::install("your_package_name")
     ```

4. Capture the environment state and create `renv.lock` file

     ```R
     renv::snapshot()
     ```

5. Include `renv.lock` in the module folder
6. Create a `post-link.sh` script and make it executable that restores the renv environment:

   ```bash
   #!/bin/bash
   R -e "renv::restore()"
   ```

7. Create an environment.yml that install `r-renv` and execute `post-link.sh`

     ```yaml
     name: your_env_name
     channels:
       - conda-forge
       - r
       - defaults
     dependencies:
       - r-base=4.3.0
       - r-renv
       # other dependencies
      run_exports:
         - post-link/noarch::post-link
     ```
